name: Java CI with Brachyura

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 17

      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            .brachyura
            ~/.brachyura
          key: ${{ runner.os }}-brachyura-${{ hashFiles('**/Buildscript.java') }}
          restore-keys: ${{ runner.os }}-brachyura

      - name: Build with Brachyura
        run: java -jar brachyura-bootstrap-0.jar build
